#!/bin/bash


if [ ! -v aolconfFLAG ]; then
echo "ERROR: This script should be called from aolconf main script"
exit
fi












# =====================================================
# ======== PREDICTIVE CONTROL  ========================
# =====================================================

if [ $state = "menupredictivecontrol" ]; then
stateok=1

menuname="PREDICTIVE CONTROL"


stringcenter "HELP"
menuitems=( "H" "\Zb\Zr\Z4$string\Zn" )
menuitems+=( " " " ")


# hardware latency (frames)
loophlat="2.1"
file="./conf/conf_hardlatency_frame.txt"
if [ -f "$file" ]; then
loophlat=$( cat $file )
fi

# software latency (frame)
loopslat="0.6"
file="./conf/conf_wfsmextrlatency_frame.txt"
if [ -f "$file" ]; then
loopclat=$( cat $file )
fi
lat=$(awk "BEGIN {printf \"%.3f\",${loophlat}+${loopclat}}")



stringcenter "MEASURE TIMING"
menuitems+=( "0 ->" "\Zb\Zr$string\Zn" )
menuitems+=( " " " ")
menuitems+=( "mt" "Measure Timing (-> timingstats/timingReport.txt)    $loophlat + $loopslat = $lat")
menuitems+=( " " " ")







stringcenter "PREDICTIVE CONTROL: COMPUTE FILTER(S)"
menuitems+=( "1 ->" "\Zb\Zr$string\Zn" )

menuitems+=( " " " ")
file="./conf/conf_PForder.txt"
if [ -f $file ]; then
PForder=$(cat $file)
else
echo "0" > $file
PForder=$(cat $file)
fi

menuitems+=( "PFord" "[$PForder] Select Predictive Filter order" )
menuitems+=( " " " latency = $lat frames")


menuitems+=( "sellat" "Select Latest telemetry files for filter computation" )
fname=$(ls -lh ./PredictiveControl/modeval_ol.fits )
fnamel=$( echo $fname |  awk '{print $NF}' )
menuitems+=( "" "FILE : $fnamel" )
menuitems+=( "mkPSDs" "Create open and closed loop PSDs of selected OL / CL telemetry" )
menuitems+=( "" "" )

file="./conf/conf_predcontr_blockSel.txt"
if [ -f $file ]; then
blockSel=$(cat $file)
else
echo "0" > $file
blockSel=$(cat $file)
fi
menuitems+=( "selB" "[$blockSel] Select block" )

menuitems+=( "ARPFb" "AO find optimal AR linear predictive filter - single block" )
menuitems+=( " " " ")







menuitems+=( "ARPF" "AO find optimal AR linear predictive filter" )



menuitems+=( " " " ")
menuitems+=( " " " ")
stringcenter "PREDICTIVE CONTROL: APPLY FILTER(S)"
menuitems+=( "2 ->" "\Zb\Zr$string\Zn" )
menuitems+=( " " " ")

menuitems+=( " " " ")
menuitems+=( "sellatC" "Select Latest telemetry files for filter correction" )
fname=$(ls -lh ./PredictiveControl/modeval_ol_C.fits )
fnamel=$( echo $fname |  awk '{print $NF}' )
menuitems+=( "" "$fnamel" )
menuitems+=( "" "" )


menuitems+=( " " " ")
menuitems+=( "PFapply" "Apply Predictive Filter" )
menuitems+=( "PFapplyb" "Apply Predictive Filter - single block" )




dialog --colors --title "PREDICTIVE CONTROL - LOOP ${LOOPNUMBER}" --ok-label " Select " --cancel-label "Top" --help-button --help-label "Exit" --default-item "${menurecord_default}" --menu "$menuname"  $nbwlines $nbwcols $nbwlines "${menuitems[@]}"  2> $tempfile



retval=$?
choiceval=$(cat $tempfile)
menurecord_default="$choiceval"
state="menupredictivecontrol"
case $retval in
   0) # Monitor
	case $choiceval in

  
  mt)
mkdir -p timingstats
./auxscripts/aolMeasureTiming > timingstats/timingReport.txt
;;
  
  
	sellat)
./auxscripts/selectLatestTelemetry
;;
  
	mkPSDs)
./auxscripts/processTelemetryPSDs
;;
  
	selB)
exec 3>&1;
blockSel=$(dialog --inputbox "Select block" 0 0 "$blockSel" 2>&1 1>&3);
exec 3>&-;
echo "$blockSel" > ./conf/conf_predcontr_blockSel.txt
;;

	PFord)
exec 3>&1;
PForder=$(dialog --inputbox "Select predictive filter order" 0 0 "$PForder" 2>&1 1>&3);
exec 3>&-;
echo "$PForder" > ./conf/conf_PForder.txt
;;


    ARPF)
echo "./auxscripts/aolARPF \"./PredictiveControl/modeval_ol.fits\" $lat $PForder" > cmd.txt
./auxscripts/aolARPF "./PredictiveControl/modeval_ol.fits" $lat $PForder
;;

    ARPFb)
echo "./auxscripts/aolARPFblock \"./PredictiveControl/modeval_ol.fits\"  $blockSel $lat $PForder" > cmd.txt
./auxscripts/aolARPFblock "./PredictiveControl/modeval_ol.fits"  $blockSel $lat $PForder
;;


	sellatC)
./auxscripts/selectLatestTelemetry -c
;;
  
  
	PFapply)
./auxscripts/aolApplyARPF "./PredictiveControl/modeval_ol_C.fits" "./PredictiveControl/outPF.fits" $lat
;;

esac
;; 
   1) state="menutop";;   
  2) state="menuexit";;
   255) state="menuexit";;
esac

fi






