#!/bin/bash


if [ ! -v aolconfFLAG ]; then
echo "ERROR: This script should be called from aolconf main script"
exit
fi











function recordanalizeWFS {
NBframes="$1"
   	mkdir -p ./rec
  	tmuxname="aol${LOOPNUMBER}-ctr"
	rm ./rec/imWFS0rec.fits
	sleep 0.2
	tmux new-session -d -s $tmuxname
	sleep 0.2
  	tmux send-keys -t $tmuxname "rm imWFS0rec" C-m
	datestr=`date -u +%Y-%m-%d_%H:%M:%S`
	tmux send-keys -t $tmuxname "$execname -n aolrec" C-m
	if [ "$CPUconfRT" -eq "1" ];then
    tmux send-keys -t $tmuxname "csetpmove system" C-m
	fi
	tmux send-keys -t $tmuxname "imgstreamrec aol${LOOPNUMBER}_imWFS0 $1 imWFS0rec " C-m	
	tmux send-keys -t $tmuxname "savefits imWFS0rec \"rec/rec_${datestr}_imWFS0rec.fits\"" C-m
	tmux send-keys -t $tmuxname "readshmim aol${LOOPNUMBER}_wfsref0" C-m
	tmux send-keys -t $tmuxname "readshmim aol${LOOPNUMBER}_wfsref" C-m
	tmux send-keys -t $tmuxname "readshmim aol${LOOPNUMBER}_respM" C-m
	tmux send-keys -t $tmuxname "readshmim aol${LOOPNUMBER}_DMmodes" C-m
	tmux send-keys -t $tmuxname "rm outcoeff" C-m
	tmux send-keys -t $tmuxname "aolsig2mcoeff imWFS0rec aol${LOOPNUMBER}_wfsref aol${LOOPNUMBER}_respM outcoeff" C-m
	tmux send-keys -t $tmuxname "savefits aol${LOOPNUMBER}_wfsref0 \"./rec/rec_${datestr}_aol${LOOPNUMBER}_wfsref0.fits\"" C-m
	tmux send-keys -t $tmuxname "savefits aol${LOOPNUMBER}_wfsref \"./rec/rec_${datestr}_aol${LOOPNUMBER}_wfsref.fits\"" C-m
    tmux send-keys -t $tmuxname "savefits aol${LOOPNUMBER}_respM \"./rec/rec_${datestr}_aol${LOOPNUMBER}_respM.fits\"" C-m
    tmux send-keys -t $tmuxname "savefits aol${LOOPNUMBER}_DMmodes \"./rec/rec_${datestr}_aol${LOOPNUMBER}_DMmodes.fits\"" C-m
    tmux send-keys -t $tmuxname "savefits outcoeff \"./rec/rec_${datestr}_mcoeffs.fits\"" C-m
	tmux send-keys -t $tmuxname "savefits aol${LOOPNUMBER}_imWFS0rec \"./rec/rec_${datestr}_imWFS0.fits\"" C-m
	tmux send-keys -t $tmuxname "!mv mode_stats.txt ./rec/rec_${datestr}_modestats.txt" C-m
}





#
# CONVENTIONS
#
# logging status is in file : ./status/stat_log_<streamname>.txt 
# associated bash variable is logstat_<streamname1> (0 or 1), where <streamname1> does not include loop number or "_" ("aol0_modeval" -> "logstat_aolmodeval")
#
# menu entries are "l<streamname>ON" and "l<streamname>OFF"
#



# =====================================================
# ======== RECORD/ANALYZE  ============================
# =====================================================

if [ $state = "menurecord" ]; then
stateok=1

menuname="RECORD / ANALYZE"


stringcenter "HELP"
menuitems=( "H" "\Zb\Zr\Z4$string\Zn" )
menuitems+=( " " " " )


stringcenter "DATA LOGGING"
menuitems+=( "1 ->" "\Zb\Zr$string\Zn" )


savedir=$( cat ./conf/conf_savedir_name.txt )
datestr=`date -u +%Y%m%d`
menuitems+=( "sdir" "[${savedir}] Save directory prefix -> $savedir/$datestr")

file="./status/stat_log_aol${LOOPNUMBER}_wfsim.txt"
logwfsimstat=$( cat $file )
if [[ -f "$file" && ( "$logwfsimstat" = "0" || "$logwfsimstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
fi


file="./status/stat_log_aol${LOOPNUMBER}_wfsref.txt"
logwfsrefstat=$( cat $file )
if [[ -f "$file" && ( "$logwfsrefstat" = "0" || "$logwfsrefstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
fi



ConfReadParam logMode "0"; logMode="$paramvalue" # LOG mode



stringcenter "DATA LOGGING MODE: $logMode"
menuitems+=( " " "\Zb\Zr$string\Zn" )

if [ "$logMode" = "0" ]; then
menuitems+=("slogM0" "\Z1\Zr Log mode = 0  - NEVER LOG \Zn" )
else
menuitems+=( "slogM0" "Set Log mode 0 : NEVER LOG" )
fi

if [ "$logMode" = "1" ]; then
menuitems+=( "slogM1" "\Z1\Zr Log mode = 1  - LOG WHEN LOOP CLOSED\Zn" )
else
menuitems+=( "slogM1" "Set Log mode 1 : LOG WHEN LOOP CLOSED" )
fi

if [ "$logMode" = "2" ]; then
menuitems+=( "slogM2" "\Z1\Zr Log mode = 2 -  ALWAYS LOG\Zn" )
else
menuitems+=( "slogM2" "Set Log mode 2 : ALWAYS LOG" )
fi

menuitems+=( " " " " )

menuitems+=( "logON"        " START logging ALL telemetry")
menuitems+=( "logOFF"       " STOP  logging ALL telemetry")
menuitems+=( "logKILL"      " KILL  all telemetry logging processes")
menuitems+=( " " " " )






streamname="wfsim"
infostring="WFS input image"
cmdON="lwfsim0"

startlogstring=$( printf "START logging %-25s   %s\n" "$streamname" "$infostring" )
stoplogstring=$( printf "\Z1\ZrSTOP logging %-25s\Zn   %s\n" "$streamname" "$infostring" )
file="./status/stat_log_aol${LOOPNUMBER}_${streamname}.txt"
logstat=$( cat $file )
if [[ -f "$file" && ( "$logstat" = "0" || "$logstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logstat="0"
fi
if [ "${logstat}" = "0" ];
then
menuitems+=( "$cmdON" "$startlogstring" )
else
menuitems+=( "lwfsim0" "$stoplogstring" )
fi




file="./status/stat_log_aol${LOOPNUMBER}_wfsref0.txt"
logwfsref0stat=$( cat $file )
if [[ -f "$file" && ( "$logwfsref0stat" = "0" || "$logwfsref0stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logwfsref0stat="0"
fi
if [ "${logwfsref0stat}" = "0" ];
then
menuitems+=( "lwfsref01" "START logging aol${LOOPNUMBER}_wfsref0              WFS reference0" )
else
menuitems+=( "lwfsref00" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_wfsref0\Zn               WFS reference0\Zn" )
fi


file="./status/stat_log_aol${LOOPNUMBER}_wfsref.txt"
logwfsrefstat=$( cat $file )
if [[ -f "$file" && ( "$logwfsrefstat" = "0" || "$logwfsrefstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logwfsrefstat="0"
fi
if [ "${logwfsrefstat}" = "0" ];
then
menuitems+=( "lwfsref1" "START logging aol${LOOPNUMBER}_wfsref               WFS reference" )
else
menuitems+=( "lwfsref0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_wfsref\Zn                WFS reference\Zn" )
fi

menuitems+=( " " " " )




file="./status/stat_log_aol${LOOPNUMBER}_gainb.txt"
loggainbstat=$( cat $file )
if [[ -f "$file" && ( "$loggainbstat" = "0" || "$loggainbstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
loggainbstat="0"
fi
if [ "${loggainbstat}" = "0" ];
then
menuitems+=( "lgainb1" "START logging aol${LOOPNUMBER}_gainb                Block gain" )
else
menuitems+=( "lgainb0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_gainb\Zn                Block gain\Zn" )
fi



file="./status/stat_log_aol${LOOPNUMBER}_DMmode_GAIN.txt"
logDMmodeGAINstat=$( cat $file )
if [[ -f "$file" && ( "$logDMmodeGAINstat" = "0" || "$logDMmodeGAINstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logDMmodeGAINstat="0"
fi
if [ "${logDMmodeGAINstat}" = "0" ];
then
menuitems+=( "ldmmodegain1" "START logging aol${LOOPNUMBER}_DMmode_GAIN          DM mode gain" )
else
menuitems+=( "ldmmodegain0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_DMmode_GAIN\Zn         DM mode gain\Zn" )
fi




file="./status/stat_log_aol${LOOPNUMBER}_limitb.txt"
loglimitbstat=$( cat $file )
if [[ -f "$file" && ( "$loglimitbstat" = "0" || "$loglimitbstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
loglimitbstat="0"
fi
if [ "${loglimitbstat}" = "0" ];
then
menuitems+=( "llimitb1" "START logging aol${LOOPNUMBER}_limitb                Block limit" )
else
menuitems+=( "llimitb0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_limitb\Zn                Block limit\Zn" )
fi



file="./status/stat_log_aol${LOOPNUMBER}_DMmode_LIMIT.txt"
logDMmodeLIMITstat=$( cat $file )
if [[ -f "$file" && ( "$logDMmodeLIMITstat" = "0" || "$logDMmodeLIMITstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logDMmodeLIMITstat="0"
fi
if [ "${logDMmodeLIMITstat}" = "0" ];
then
menuitems+=( "ldmmodelimit1" "START logging aol${LOOPNUMBER}_DMmode_LIMIT         DM mode limit" )
else
menuitems+=( "ldmmodelimit0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_DMmode_LIMIT\Zn          DM mode limit\Zn" )
fi



file="./status/stat_log_aol${LOOPNUMBER}_multfb.txt"
logmultfbstat=$( cat $file )
if [[ -f "$file" && ( "$logmultfbstat" = "0" || "$logmultfbstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logmultfbstat="0"
fi
if [ "${logmultfbstat}" = "0" ];
then
menuitems+=( "lmultfb1" "START logging aol${LOOPNUMBER}_multfb               Block mult factor" )
else
menuitems+=( "lmultfb0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_multfb\Zn               Block mult factor\Zn" )
fi



file="./status/stat_log_aol${LOOPNUMBER}_DMmode_MULTF.txt"
logDMmodeMULTFstat=$( cat $file )
if [[ -f "$file" && ( "$logDMmodeMULTFstat" = "0" || "$logDMmodeMULTFstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logDMmodeMULTFstat="0"
fi
if [ "${logDMmodeMULTFstat}" = "0" ];
then
menuitems+=( "ldmmodemultf1" "START logging aol${LOOPNUMBER}_DMmode_MULTF         DM mode mult factor" )
else
menuitems+=( "ldmmodemultf0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_DMmode_MULTF\Zn        DM mode mult factor\Zn" )
fi




menuitems+=( " " " " )



file="./status/stat_log_dm${DMindex}disp.txt"
logdmdispstat=$( cat $file )
if [[ -f "$file" && ( "$logdmdispstat" = "0" || "$logdmdispstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdispstat=0
fi
if [ "${logdmdispstat}" = "0" ];
then
menuitems+=( "ldmdisp1" "START logging dm${DMindex}disp                  total DM displacement" )
else
menuitems+=( "ldmdisp0" "\Z1\ZrSTOP logging dm${DMindex}disp\Zn                   total DM displacement" )
fi


file="./status/stat_log_dm${DMindex}disp00.txt"
logdmdisp00stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp00stat" = "0" || "$logdmdisp00stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp00stat=0
fi
if [ "${logdmdisp00stat}" = "0" ];
then
menuitems+=( "ldmdisp001" "START logging dm${DMindex}disp00                DM channel 00" )
else
menuitems+=( "ldmdisp000" "\Z1\ZrSTOP logging dm${DMindex}disp00\Zn                 DM channel 00" )
fi



file="./status/stat_log_dm${DMindex}disp01.txt"
logdmdisp01stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp01stat" = "0" || "$logdmdisp01stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp01stat=0
fi
if [ "${logdmdisp01stat}" = "0" ];
then
menuitems+=( "ldmdisp011" "START logging dm${DMindex}disp01                DM channel 01" )
else
menuitems+=( "ldmdisp010" "\Z1\ZrSTOP logging dm${DMindex}disp01\Zn                 DM channel 01" )
fi


file="./status/stat_log_dm${DMindex}disp02.txt"
logdmdisp02stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp02stat" = "0" || "$logdmdisp02stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp02stat=0
fi
if [ "${logdmdisp02stat}" = "0" ];
then
menuitems+=( "ldmdisp021" "START logging dm${DMindex}disp02                DM channel 02" )
else
menuitems+=( "ldmdisp020" "\Z1\ZrSTOP logging dm${DMindex}disp02\Zn                 DM channel 02" )
fi


file="./status/stat_log_dm${DMindex}disp03.txt"
logdmdisp03stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp03stat" = "0" || "$logdmdisp03stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp03stat=0
fi
if [ "${logdmdisp03stat}" = "0" ];
then
menuitems+=( "ldmdisp031" "START logging dm${DMindex}disp03                DM channel 03" )
else
menuitems+=( "ldmdisp030" "\Z1\ZrSTOP logging dm${DMindex}disp03\Zn                 DM channel 03" )
fi


file="./status/stat_log_dm${DMindex}disp04.txt"
logdmdisp04stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp04stat" = "0" || "$logdmdisp04stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp04stat=0
fi
if [ "${logdmdisp04stat}" = "0" ];
then
menuitems+=( "ldmdisp041" "START logging dm${DMindex}disp04                DM channel 04" )
else
menuitems+=( "ldmdisp040" "\Z1\ZrSTOP logging dm${DMindex}disp04\Zn                 DM channel 04" )
fi


file="./status/stat_log_dm${DMindex}disp05.txt"
logdmdisp05stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp05stat" = "0" || "$logdmdisp05stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp05stat=0
fi
if [ "${logdmdisp05stat}" = "0" ];
then
menuitems+=( "ldmdisp051" "START logging dm${DMindex}disp05                DM channel 05" )
else
menuitems+=( "ldmdisp050" "\Z1\ZrSTOP logging dm${DMindex}disp05\Zn                 DM channel 05" )
fi



file="./status/stat_log_dm${DMindex}disp06.txt"
logdmdisp06stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp06stat" = "0" || "$logdmdisp06stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp06stat=0
fi
if [ "${logdmdisp06stat}" = "0" ];
then
menuitems+=( "ldmdisp061" "START logging dm${DMindex}disp06                DM channel 06" )
else
menuitems+=( "ldmdisp060" "\Z1\ZrSTOP logging dm${DMindex}disp06\Zn                 DM channel 06" )
fi


file="./status/stat_log_dm${DMindex}disp07.txt"
logdmdisp07stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp07stat" = "0" || "$logdmdisp07stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp07stat=0
fi
if [ "${logdmdisp07stat}" = "0" ];
then
menuitems+=( "ldmdisp071" "START logging dm${DMindex}disp07                DM channel 07" )
else
menuitems+=( "ldmdisp070" "\Z1\ZrSTOP logging dm${DMindex}disp07\Zn                 DM channel 07" )
fi


file="./status/stat_log_dm${DMindex}disp08.txt"
logdmdisp08stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp08stat" = "0" || "$logdmdisp08stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp08stat=0
fi
if [ "${logdmdisp08stat}" = "0" ];
then
menuitems+=( "ldmdisp081" "START logging dm${DMindex}disp08                DM channel 08" )
else
menuitems+=( "ldmdisp080" "\Z1\ZrSTOP logging dm${DMindex}disp08\Zn                 DM channel 08" )
fi


file="./status/stat_log_dm${DMindex}disp09.txt"
logdmdisp09stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp09stat" = "0" || "$logdmdisp09stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp09stat=0
fi
if [ "${logdmdisp09stat}" = "0" ];
then
menuitems+=( "ldmdisp091" "START logging dm${DMindex}disp09                DM channel 09" )
else
menuitems+=( "ldmdisp090" "\Z1\ZrSTOP logging dm${DMindex}disp09\Zn                 DM channel 09" )
fi


file="./status/stat_log_dm${DMindex}disp10.txt"
logdmdisp10stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp10stat" = "0" || "$logdmdisp10stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp10stat=0
fi
if [ "${logdmdisp10stat}" = "0" ];
then
menuitems+=( "ldmdisp101" "START logging dm${DMindex}disp10                DM channel 10" )
else
menuitems+=( "ldmdisp100" "\Z1\ZrSTOP logging dm${DMindex}disp10\Zn                 DM channel 10" )
fi


file="./status/stat_log_dm${DMindex}disp11.txt"
logdmdisp11stat=$( cat $file )
if [[ -f "$file" && ( "$logdmdisp11stat" = "0" || "$logdmdisp11stat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logdmdisp11stat=0
fi
if [ "${logdmdisp11stat}" = "0" ];
then
menuitems+=( "ldmdisp111" "START logging dm${DMindex}disp11                DM channel 11" )
else
menuitems+=( "ldmdisp110" "\Z1\ZrSTOP logging dm${DMindex}disp11\Zn                 DM channel 11" )
fi

menuitems+=( " " " " )


ConfReadParam CMMODE "0"; CMMODE="$paramvalue"
if [ "$CMMODE" = "0" ]; then

file="./status/stat_log_modeval.txt"
logmodevalstat=$( cat $file )
if [[ -f "$file" && ( "$logmodevalstat" = "0" || "$logmodevalstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logmodevalstat=0
fi
if [ "${logmodevalstat}" = "0" ];
then
menuitems+=( "lmodeval1" "START logging aol${LOOPNUMBER}_modeval              WFS-measured mode values" )
else
menuitems+=( "lmodeval0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_modeval\Zn               WFS-measured mode values" )
fi

file="./status/stat_log_modeval_dm_corr.txt"
logmodevaldmcorrstat=$( cat $file )
if [[ -f "$file" && ( "$logmodevaldmcorrstat" = "0" || "$logmodevaldmcorrstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logmodevaldmcorrstat=0
fi
if [ "${logmodevaldmcorrstat}" = "0" ];
then
menuitems+=( "lmodevaldmcorr1" "START logging aol${LOOPNUMBER}_modeval_dm_corr      Correction mode values (after modal gains)" )
else
menuitems+=( "lmodevaldmcorr0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_modeval_dm_corr\Zn       Correction mode values (after modal gains)" )
fi


file="./status/stat_log_modeval_dm_now.txt"
logmodevaldmnowstat=$( cat $file )
if [[ -f "$file" && ( "$logmodevaldmnowstat" = "0" || "$logmodevaldmnowstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logmodevaldmnowstat=0
fi
if [ "${logmodevaldmnowstat}" = "0" ];
then
menuitems+=( "lmodevaldmnow1" "START logging aol${LOOPNUMBER}_modeval_dm_now       Correction mode values (after predictive mixing)" )
else
menuitems+=( "lmodevaldmnow0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_modeval_dm_now\Zn        Correction mode values (after predictive mixing)" )
fi



file="./status/stat_log_modeval_dm_now_filt.txt"
logmodevaldmnowfiltstat=$( cat $file )
if [[ -f "$file" && ( "$logmodevaldmnowfiltstat" = "0" || "$logmodevaldmnowfiltstat" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
logmodevaldmnowfiltstat=0
fi
if [ "${logmodevaldmnowfiltstat}" = "0" ];
then
menuitems+=( "lmodevaldmnowfilt1" "START logging aol${LOOPNUMBER}_modeval_dm_now_filt  Correction mode values (after clipping)" )
else
menuitems+=( "lmodevaldmnowfilt0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_modeval_dm_now_filt\Zn   Correction mode values (after clipping)" )
fi



file="./status/stat_log_modeval_ol.txt"
logmodevalolstat=$( cat $file )
if [[ -f "$file" && ( "$logmodevalolstat" = "0" || "$logmodevalolstat" = "1" ) ]]; then
	echo "OK"
else
	echo "0" > $file
	logmodevalolstat=0
fi
if [ "${logmodevalolstat}" = "0" ];
	then
	menuitems+=( "lmodevalol1" "START logging aol${LOOPNUMBER}_modeval_ol           Open loop mode values" )
else
	menuitems+=( "lmodevalol0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_modeval_ol\Zn            Open loop mode values" )
fi




file="./status/stat_log_modevalPF.txt"
logmodevalPFstat=$( cat $file )
if [[ -f "$file" && ( "$logmodevalPFstat" = "0" || "$logmodevalPFstat" = "1" ) ]]; then
	echo "OK"
else
	echo "0" > $file
	logmodevalPFstat=0
fi
if [ "${logmodevalPFstat}" = "0" ];
	then
	menuitems+=( "lmodevalPF1" "START logging aol${LOOPNUMBER}_modevalPF            Predictive filter error mode values" )
else
	menuitems+=( "lmodevalPF0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_modevalPF\Zn             Predictive filter mode values" )
fi



file="./status/stat_log_modevalPFsync.txt"
logmodevalPFsyncstat=$( cat $file )
if [[ -f "$file" && ( "$logmodevalPFsyncstat" = "0" || "$logmodevalPFsyncstat" = "1" ) ]]; then
	echo "OK"
else
	echo "0" > $file
	logmodevalPFsyncstat=0
fi
if [ "${logmodevalPFsyncstat}" = "0" ];
	then
	menuitems+=( "lmodevalPFsync1" "START logging aol${LOOPNUMBER}_modevalPFsync        Predictive filter error mode values, synced with open loop rec" )
else
	menuitems+=( "lmodevalPFsync0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_modevalPFsync\Zn         Predictive filter mode values, synced with open loop rec" )
fi



file="./status/stat_log_modevalPFres.txt"
logmodevalPFresstat=$( cat $file )
if [[ -f "$file" && ( "$logmodevalPFresstat" = "0" || "$logmodevalPFresstat" = "1" ) ]]; then
	echo "OK"
else
	echo "0" > $file
	logmodevalPFresstat=0
fi
if [ "${logmodevalPFresstat}" = "0" ];
	then
	menuitems+=( "lmodevalPFres1" "START logging aol${LOOPNUMBER}_modevalPFres         Measured predictive filter error mode values" )
else
	menuitems+=( "lmodevalPFres0" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_modevalPFres\Zn          Measured predictive filter mode values" )
fi




file="./status/stat_log_outPFb0.txt"
logoutPFb0stat=$( cat $file )
if [[ -f "$file" && ( "$logoutPFb0stat" = "0" || "$logoutPFb0stat" = "1" ) ]]; then
	echo "OK"
else
	echo "0" > $file
	logoutPFb0stat=0
fi
if [ "${logoutPFb0stat}" = "0" ];
	then
	menuitems+=( "loutPFb01" "START logging aol${LOOPNUMBER}_outPFb0              Predictive filter block 0" )
else
	menuitems+=( "loutPFb00" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_outPFb0\Zn               Predictive filter block 0" )
fi



file="./status/stat_log_outPFb1.txt"
logoutPFb1stat=$( cat $file )
if [[ -f "$file" && ( "$logoutPFb1stat" = "0" || "$logoutPFb1stat" = "1" ) ]]; then
	echo "OK"
else
	echo "0" > $file
	logoutPFb1stat=0
fi
if [ "${logoutPFb1stat}" = "0" ];
	then
	menuitems+=( "loutPFb11" "START logging aol${LOOPNUMBER}_outPFb1              Predictive filter block 1" )
else
	menuitems+=( "loutPFb10" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_outPFb1\Zn               Predictive filter block 1" )
fi


file="./status/stat_log_outPFb2.txt"
logoutPFb2stat=$( cat $file )
if [[ -f "$file" && ( "$logoutPFb2stat" = "0" || "$logoutPFb2stat" = "1" ) ]]; then
	echo "OK"
else
	echo "0" > $file
	logoutPFb2stat=0
fi
if [ "${logoutPFb2stat}" = "0" ];
	then
	menuitems+=( "loutPFb21" "START logging aol${LOOPNUMBER}_outPFb2              Predictive filter block 2" )
else
	menuitems+=( "loutPFb20" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_outPFb2\Zn               Predictive filter block 2" )
fi


file="./status/stat_log_outPFb3.txt"
logoutPFb3stat=$( cat $file )
if [[ -f "$file" && ( "$logoutPFb3stat" = "0" || "$logoutPFb3stat" = "1" ) ]]; then
	echo "OK"
else
	echo "0" > $file
	logoutPFb3stat=0
fi
if [ "${logoutPFb3stat}" = "0" ];
	then
	menuitems+=( "loutPFb31" "START logging aol${LOOPNUMBER}_outPFb3              Predictive filter block 3" )
else
	menuitems+=( "loutPFb30" "\Z1\ZrSTOP logging aol${LOOPNUMBER}_outPFb3\Zn               Predictive filter block 3" )
fi





fi








menuitems+=( " " " " )

stringcenter "TEMPORAL STATISTICS"
menuitems+=( "2 ->" "\Zb\Zr$string\Zn" )

file="./conf/conf_dmCavecoeff.txt"
dmCavecoeff=$( cat $file )
menuitems+=( "setdmCaveC" "[${dmCavecoeff}] Set dmC averaging coefficient value" )


file="./status/stat_taveC_ON.txt"
taveC_ON=$( cat $file )
if [[ -f "$file" && ( "$taveC_ON" = "0" || "$taveC_ON" = "1" ) ]]; then
echo "OK"
else
echo "0" > $file
taveC_ON=0
fi
if [ "${taveC_ON}" = "0" ];
then
menuitems+=( "taveC1" "START temporal average of DM correction -> aol2_dmCave" )
else
menuitems+=( "taveC0" "STOP temporal average of DM correction  -> aol2_cmCave" )
fi


menuitems+=( " " " " )

stringcenter "RECORD TIME SEQUENCES"
menuitems+=( "3 ->" "\Zb\Zr$string\Zn" )
menuitems+=( "rins" "Record / analyze single instantaneous loop state to ./recinst/ directory" )
menuitems+=( "rec1" "Record / analyze     10 WFS frames" )
menuitems+=( "rec2" "Record / analyze    100 WFS frames" )
menuitems+=( "rec3" "Record / analyze   1000 WFS frames" )
menuitems+=( "rec4" "Record / analyze  10000 WFS frames" )


dialog --colors --title "RECORD and ANALYZE  - LOOP ${LOOPNUMBER}" --ok-label " Select " --cancel-label "Top" --help-button --help-label "Exit" --default-item "${menurecord_default}" --menu "$menuname"  $nbwlines $nbwcols $nbwlines "${menuitems[@]}"  2> $tempfile



retval=$?
choiceval=$(cat $tempfile)
menurecord_default="$choiceval"
state="menurecord"
case $retval in
   0) # Monitor
	case $choiceval in

    sdir)
exec 3>&1;
savedir=$(dialog --inputbox "savedir" 0 0 "$savedir" 2>&1 1>&3);
exec 3>&-;
echo "$savedir" > ./conf/conf_savedir_name.txt
;;


    slogM0)
logMode="0"
echo "0" > "./conf/conf_logmode.txt"
stop_Telemetrylog_all
menurecord_default="slogM0"
;;
    slogM1)
logMode="1"
echo "1" > "./conf/conf_logmode.txt"
loopON=$( cat ./status/stat_loopON.txt )
aoconflog "TEST: loopON=$loopON"
if [ "$loopON" = " ON" ];
then
start_Telemetrylog_all
fi
if [ "$loopON" = "OFF" ];
then
stop_Telemetrylog_all
fi
menurecord_default="slogM1"
;;
    slogM2)
logMode="2"
echo "2" > "./conf/conf_logmode.txt"
start_Telemetrylog_all
menurecord_default="slogM2"
;;



    logON)
start_Telemetrylog_all # function in aolconf_logfuncs
;;

    logOFF)
stop_Telemetrylog_all
;;

    logKILL)
kill_Telemetrylog_all
;;


    lwfsim1)
startstreamlog aol${LOOPNUMBER}_wfsim
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_wfsim.txt"
menurecord_default="lwfsim0"
;;
    lwfsim0)
stopstreamlog aol${LOOPNUMBER}_wfsim
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_wfsim.txt"
menurecord_default="lwfsim1"
;;


    lwfsref01)
startstreamlog aol${LOOPNUMBER}_wfsref0
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_wfsref0.txt"
menurecord_default="lwfsref00"
;;
    lwfsref00)
stopstreamlog aol${LOOPNUMBER}_wfsref0
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_wfsref0.txt"
menurecord_default="lwfsref01"
;;


    lwfsref1)
startstreamlog aol${LOOPNUMBER}_wfsref
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_wfsref.txt"
menurecord_default="lwfsref0"
;;
    lwfsref0)
stopstreamlog aol${LOOPNUMBER}_wfsref
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_wfsref.txt"
menurecord_default="lwfsref1"
;;





    lgainb1)
startstreamlog aol${LOOPNUMBER}_gainb
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_gainb.txt"
menurecord_default="lgainb0"
;;
    lgainb0)
stopstreamlog aol${LOOPNUMBER}_gainb
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_gainb.txt"
menurecord_default="lgainb1"
;;


    ldmmodegain1)
startstreamlog aol${LOOPNUMBER}_DMmode_GAIN
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_GAIN.txt"
menurecord_default="ldmmodegain0"
;;
    ldmmodegain0)
stopstreamlog aol${LOOPNUMBER}_DMmode_GAIN
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_GAIN.txt"
menurecord_default="ldmmodegain1"
;;


    llimitb1)
startstreamlog aol${LOOPNUMBER}_limitb
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_limitb.txt"
menurecord_default="llimitb0"
;;
    llimit0)
stopstreamlog aol${LOOPNUMBER}_limitb
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_limitb.txt"
menurecord_default="llimitb1"
;;


    ldmmodelimit1)
startstreamlog aol${LOOPNUMBER}_DMmode_LIMIT
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_LIMIT.txt"
menurecord_default="ldmmodelimit0"
;;
    ldmmodelimit0)
stopstreamlog aol${LOOPNUMBER}_DMmode_LIMIT
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_LIMIT.txt"
menurecord_default="ldmmodelimit1"
;;



    lmultfb1)
startstreamlog aol${LOOPNUMBER}_multfb
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_multfb.txt"
menurecord_default="lmultfb0"
;;
    lmultfb0)
stopstreamlog aol${LOOPNUMBER}_multfb
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_multfb.txt"
menurecord_default="lmultfb1"
;;


    ldmmodemultf1)
startstreamlog aol${LOOPNUMBER}_DMmode_MULTF
echo "1" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_MULTF.txt"
menurecord_default="ldmmodemultf0"
;;
    ldmmodemultf0)
stopstreamlog aol${LOOPNUMBER}_DMmode_MULTF
echo "0" > "./status/stat_log_aol${LOOPNUMBER}_DMmode_MULTF.txt"
menurecord_default="ldmmodemultf1"
;;




    ldmdisp1)
startstreamlog dm${DMindex}disp
echo "1" > "./status/stat_log_dm${DMindex}disp.txt"
menurecord_default="ldmdisp0"
;;
    ldmdisp0)
stopstreamlog dm${DMindex}disp
echo "0" > "./status/stat_log_dm${DMindex}disp.txt"
menurecord_default="ldmdisp1"
;;


    ldmdisp001)
startstreamlog dm${DMindex}disp00
echo "1" > "./status/stat_log_dm${DMindex}disp00.txt"
menurecord_default="ldmdisp000"
;;
    ldmdisp000)
stopstreamlog dm${DMindex}disp00
echo "0" > "./status/stat_log_dm${DMindex}disp00.txt"
menurecord_default="ldmdisp001"
;;


    ldmdisp011)
startstreamlog dm${DMindex}disp01
echo "1" > "./status/stat_log_dm${DMindex}disp01.txt"
menurecord_default="ldmdisp010"
;;
    ldmdisp010)
stopstreamlog dm${DMindex}disp01
echo "0" > "./status/stat_log_dm${DMindex}disp01.txt"
menurecord_default="ldmdisp011"
;;


    ldmdisp021)
startstreamlog dm${DMindex}disp02
echo "1" > "./status/stat_log_dm${DMindex}disp02.txt"
menurecord_default="ldmdisp020"
;;
    ldmdisp020)
stopstreamlog dm${DMindex}disp02
echo "0" > "./status/stat_log_dm${DMindex}disp02.txt"
menurecord_default="ldmdisp021"send-keys -t ${tmuxname}
;;


    ldmdisp031)
startstreamlog dm${DMindex}disp03
echo "1" > "./status/stat_log_dm${DMindex}disp03.txt"
menurecord_default="ldmdisp030"
;;
    ldmdisp030)
stopstreamlog dm${DMindex}disp03
echo "0" > "./status/stat_log_dm${DMindex}disp03.txt"
menurecord_default="ldmdisp031"
;;


    ldmdisp041)
startstreamlog dm${DMindex}disp04
echo "1" > "./status/stat_log_dm${DMindex}disp04.txt"
menurecord_default="ldmdisp040"
;;
    ldmdisp040)
stopstreamlog dm${DMindex}disp04
echo "0" > "./status/stat_log_dm${DMindex}disp04.txt"
menurecord_default="ldmdisp041"
;;


    ldmdisp051)
startstreamlog dm${DMindex}disp05
echo "1" > "./status/stat_log_dm${DMindex}disp05.txt"
menurecord_default="ldmdisp050"
;;
    ldmdisp050)
stopstreamlog dm${DMindex}disp05
echo "0" > "./status/stat_log_dm${DMindex}disp05.txt"
menurecord_default="ldmdisp051"
;;


    ldmdisp061)
startstreamlog dm${DMindex}disp06
echo "1" > "./status/stat_log_dm${DMindex}disp06.txt"
menurecord_default="ldmdisp060"
;;
    ldmdisp060)
stopstreamlog dm${DMindex}disp06
echo "0" > "./status/stat_log_dm${DMindex}disp06.txt"
menurecord_default="ldmdisp061"
;;


    ldmdisp071)
startstreamlog dm${DMindex}disp07
echo "1" > "./status/stat_log_dm${DMindex}disp07.txt"
menurecord_default="ldmdisp070"
;;
    ldmdisp070)
stopstreamlog dm${DMindex}disp07
echo "0" > "./status/stat_log_dm${DMindex}disp07.txt"
menurecord_default="ldmdisp071"
;;


    ldmdisp081)
startstreamlog dm${DMindex}disp08
echo "1" > "./status/stat_log_dm${DMindex}disp08.txt"
menurecord_default="ldmdisp080"
;;
    ldmdisp080)
stopstreamlog dm${DMindex}disp08
echo "0" > "./status/stat_log_dm${DMindex}disp08.txt"
menurecord_default="ldmdisp081"
;;


    ldmdisp091)
startstreamlog dm${DMindex}disp09
echo "1" > "./status/stat_log_dm${DMindex}disp09.txt"
menurecord_default="ldmdisp090"
;;
    ldmdisp090)
stopstreamlog dm${DMindex}disp09
echo "0" > "./status/stat_log_dm${DMindex}disp09.txt"
menurecord_default="ldmdisp091"
;;


    ldmdisp101)
startstreamlog dm${DMindex}disp10
echo "1" > "./status/stat_log_dm${DMindex}disp10.txt"
menurecord_default="ldmdisp100"
;;
    ldmdisp100)
stopstreamlog dm${DMindex}disp10
echo "0" > "./status/stat_log_dm${DMindex}disp10.txt"
menurecord_default="ldmdisp101"
;;


    ldmdisp111)
startstreamlog dm${DMindex}disp10
echo "1" > "./status/stat_log_dm${DMindex}disp11.txt"
menurecord_default="ldmdisp110"
;;
    ldmdisp110)
stopstreamlog dm${DMindex}disp11
echo "0" > "./status/stat_log_dm${DMindex}disp11.txt"
menurecord_default="ldmdisp111"
;;




    lmodeval1)
startstreamlog aol${LOOPNUMBER}_modeval
echo "1" > "./status/stat_log_modeval.txt"
menurecord_default="lmodeval0"
;;
    lmodeval0)
stopstreamlog aol${LOOPNUMBER}_modeval
echo "0" > "./status/stat_log_modeval.txt"
menurecord_default="lmodeval1"
;;



    lmodevaldmnow1)
startstreamlog aol${LOOPNUMBER}_modeval_dm_now
echo "1" > "./status/stat_log_modeval_dm_now.txt"
menurecord_default="lmodevaldmnow0"
;;
    lmodevaldmnow0)
stopstreamlog aol${LOOPNUMBER}_modeval_dm_now
echo "0" > "./status/stat_log_modeval_dm_now.txt"
menurecord_default="lmodevaldmnow1"
;;


    lmodevaldmnowfilt1)
startstreamlog aol${LOOPNUMBER}_modeval_dm_now_filt
echo "1" > "./status/stat_log_modeval_dm_now_filt.txt"
menurecord_default="lmodevaldmnowfilt0"
;;
    lmodevaldmnowfilt0)
stopstreamlog aol${LOOPNUMBER}_modeval_dm_now_filt
echo "0" > "./status/stat_log_modeval_dm_now_filt.txt"
menurecord_default="lmodevaldmnowfilt1"
;;





    lmodevalol1)
startstreamlog aol${LOOPNUMBER}_modeval_ol
echo "1" > "./status/stat_log_modeval_ol.txt"
menurecord_default="lmodevalol0"
;;
    lmodevalol0)
stopstreamlog aol${LOOPNUMBER}_modeval_ol
echo "0" > "./status/stat_log_modeval_ol.txt"
menurecord_default="lmodevalol1"
;;



    lmodevalPF1)
startstreamlog aol${LOOPNUMBER}_modevalPF
echo "1" > "./status/stat_log_modevalPF.txt"
menurecord_default="lmodevalPF0"
;;
    lmodevalPF0)
stopstreamlog aol${LOOPNUMBER}_modevalPF
echo "0" > "./status/stat_log_modevalPF.txt"
menurecord_default="lmodevalPF1"
;;



    lmodevalPFsync1)
startstreamlog aol${LOOPNUMBER}_modevalPFsync
echo "1" > "./status/stat_log_modevalPFsync.txt"
menurecord_default="lmodevalPFsync0"
;;
    lmodevalPFsync0)
stopstreamlog aol${LOOPNUMBER}_modevalPFsync
echo "0" > "./status/stat_log_modevalPFsync.txt"
menurecord_default="lmodevalPFsync1"
;;



    lmodevalPFres1)
startstreamlog aol${LOOPNUMBER}_modevalPFres
echo "1" > "./status/stat_log_modevalPFres.txt"
menurecord_default="lmodevalPFres0"
;;
    lmodevalPFres0)
stopstreamlog aol${LOOPNUMBER}_modevalPFres
echo "0" > "./status/stat_log_modevalPFres.txt"
menurecord_default="lmodevalPFres1"
;;


    loutPFb01)
startstreamlog aol${LOOPNUMBER}_outPFb0
echo "1" > "./status/stat_log_outPFb0.txt"
menurecord_default="loutPFb00"
;;
    loutPFb00)
stopstreamlog aol${LOOPNUMBER}_outPFb0
echo "0" > "./status/stat_log_outPFb0.txt"
menurecord_default="loutPFb01"
;;




    loutPFb11)
startstreamlog aol${LOOPNUMBER}_outPFb1
echo "1" > "./status/stat_log_outPFb1.txt"
menurecord_default="loutPFb10"
;;
    loutPFb10)
stopstreamlog aol${LOOPNUMBER}_outPFb1
echo "0" > "./status/stat_log_outPFb1.txt"
menurecord_default="loutPFb11"
;;




    loutPFb21)
startstreamlog aol${LOOPNUMBER}_outPFb2
echo "1" > "./status/stat_log_outPFb2.txt"
menurecord_default="loutPFb20"
;;
    loutPFb20)
stopstreamlog aol${LOOPNUMBER}_outPFb2
echo "0" > "./status/stat_log_outPFb2.txt"
menurecord_default="loutPFb21"
;;




    loutPFb31)
startstreamlog aol${LOOPNUMBER}_outPFb3
echo "1" > "./status/stat_log_outPFb3.txt"
menurecord_default="loutPFb30"
;;
    loutPFb30)
stopstreamlog aol${LOOPNUMBER}_outPFb3
echo "0" > "./status/stat_log_outPFb3.txt"
menurecord_default="loutPFb31"
;;

















	setdmCaveC)
exec 3>&1;
dmCavecoeff=$(dialog --inputbox "dmC averaging coeff" 0 0 "$dmCavecoeff" 2>&1 1>&3);
exec 3>&-;
echo "$dmCavecoeff" > ./conf/conf_dmCavecoeff.txt
aoconflog "setting dmC averaging coeff to $dmCavecoeff"
;;

taveC1)
file="./status/stat_taveC_ON.txt"
echo "1" > $file
tmuxname="aol${LOOPNUMBER}dmCave"
sleep 0.2
tmux new-session -d -s $tmuxname
sleep 0.2
tmux send-keys -t ${tmuxname} "./auxscripts/aol_dmCave ${dmCavecoeff}" C-m
menurecord_default="taveC0"
;;

taveC0)
file="./status/stat_taveC_ON.txt"
echo "0" > $file
tmuxname="aol${LOOPNUMBER}dmCave"
tmux kill-session -t $tmuxname
menurecord_default="taveC1"
;;








    rins) 
mkdir -p recinst
tmuxname="aol${LOOPNUMBER}-ctr"
tmux send-keys -t $tmuxname "readshmim aol${LOOPNUMBER}_meas_act_active" C-m
tmux send-keys -t $tmuxname "readshmim aol${LOOPNUMBER}_meas_act" C-m
for name in contrM contrMc contrMcact dmC dmO dmdisp dmmap dmmask DMmodes dmRM dmZP2 dmZP3 gainb imWFS0 imWFS1 imWFS1RM imWFS2 meas_act_active meas_act respM wfsdark wfsim wfsmap wfsmask wfsref0 wfsref zrespM
do
tmux send-keys -t $tmuxname "savefits aol${LOOPNUMBER}_${name} \"!./recinst/aol${LOOPNUMBER}_${name}.fits\"" C-m
done
;;
    rec1) recordanalizeWFS 10;;
   	rec2) recordanalizeWFS 100;;
   	rec3) recordanalizeWFS 1000;;
   	rec4) recordanalizeWFS 10000;;
    rec5) recordanalizeWFS 100000;;
	an) processWFSrec;;
esac
;; 
   1) state="menutop";;   
  2) state="menuexit";;
   255) state="menuexit";;
esac

fi






