#!/bin/bash


if [ ! -v aolconfFLAG ]; then
echo "ERROR: This script should be called from aolconf main script"
exit
fi












# =====================================================
# ======== PREDICTIVE CONTROL  ========================
# =====================================================

if [ $state = "menupredictivecontrol" ]; then
stateok=1

menuname="PREDICTIVE CONTROL"


stringcenter "HELP"
menuitems=( "H" "\Zb\Zr\Z4$string\Zn" )
menuitems+=( " " " ")


# hardware latency (frames)
loophlat="2.1"
file="./conf/conf_hardlatency_frame.txt"
if [ -f "$file" ]; then
loophlat=$( cat $file )
fi

# software latency (frame)
loopslat="0.6"
file="./conf/conf_wfsmextrlatency_frame.txt"
if [ -f "$file" ]; then
loopslat=$( cat $file )
fi
lat=$(awk "BEGIN {printf \"%.3f\",${loophlat}+${loopslat}}")



stringcenter "TIMING PARAMETERS"
menuitems+=( "0 ->" "\Zb\Zr$string\Zn" )
menuitems+=( " " " ")

menuitems+=( "mt" "Measure Timing (-> timingstats/timingReport.txt)    $loophlat + $loopslat = $lat")

file="./conf/conf_PForder.txt"
if [ -f $file ]; then
PForder=$(cat $file)
else
echo "0" > $file
PForder=$(cat $file)
fi
menuitems+=( "PFord" "[$PForder] Select Predictive Filter order" )

file="./conf/conf_predcontr_blockSel.txt"
if [ -f $file ]; then
blockSel=$(cat $file)
else
echo "0" > $file
blockSel=$(cat $file)
fi
menuitems+=( "selB" "[$blockSel] Select block" )

menuitems+=( " " " ")




stringcenter "SINGLE FILE: COMPUTE FILTER(S)"
menuitems+=( "1 ->" "\Zb\Zr$string\Zn" )

menuitems+=( " " " ")


menuitems+=( "sellat" "Select Latest telemetry files for filter computation" )
fname=$(ls -lh ./PredictiveControl/modeval_ol.fits )
fnamel=$( echo $fname |  awk '{print $NF}' )
menuitems+=( "" "      FILE : $fnamel" )
menuitems+=( "mkPSDs" "Create open and closed loop PSDs of selected OL / CL telemetry" )
menuitems+=( "ARPFb" "AO find optimal AR linear predictive filter - single block" )
menuitems+=( "ARPF" "AO find optimal AR linear predictive filter" )



menuitems+=( " " " ")
menuitems+=( " " " ")
stringcenter "SINGLE FILE: APPLY FILTER(S)"
menuitems+=( "2 ->" "\Zb\Zr$string\Zn" )
menuitems+=( " " " ")

menuitems+=( " " " ")
menuitems+=( "sellatC" "Select Latest telemetry files for filter correction" )
fname=$(ls -lh ./PredictiveControl/modeval_ol_C.fits )
fnamel=$( echo $fname |  awk '{print $NF}' )
menuitems+=( "" "      FILE : $fnamel" )
menuitems+=( "PFapplyb" "Apply Predictive Filter - single block" )
menuitems+=( "PFapply" "Apply Predictive Filter" )


menuitems+=( " " " ")
menuitems+=( " " " ")
stringcenter "CONTINUOUS PREDICTIVE FILTER LOOP"
menuitems+=( "3 ->" "\Zb\Zr$string\Zn" )
menuitems+=( " " " ")

menuitems+=( " " " ")

file="./conf/conf_PFblock_0.txt"
if [ -f $file ]; then
PFb0start=$( cat $file | awk '{ print $1}' )
PFb0end=$( cat $file | awk '{ print $2}' )
PFb0order=$( cat $file | awk '{ print $3}' )
else
PFb0start="0"
PFb0send="2"
PFb0order="10"
PFb0lag="2.5"
echo "$PFb0start $PFb0end $PFb0order $PFb0lat" > $file
fi

menuitems+=( "PFb0sart" "[$PFb0start] set Predictive filter block 0 start" )
menuitems+=( "PFb0end" "[$PFb0end] set Predictive filter block 0 end" )
menuitems+=( "PFb0order" "[$PFb0order] set Predictive filter block 0 order" )
menuitems+=( "PFb0lag" "[$PFb0lag] set Predictive filter block 0 lag" )



dialog --colors --title "PREDICTIVE CONTROL - LOOP ${LOOPNUMBER}" --ok-label " Select " --cancel-label "Top" --help-button --help-label "Exit" --default-item "${menurecord_default}" --menu "$menuname"  $nbwlines $nbwcols $nbwlines "${menuitems[@]}"  2> $tempfile



retval=$?
choiceval=$(cat $tempfile)
menurecord_default="$choiceval"
state="menupredictivecontrol"
case $retval in
   0) # Monitor
	case $choiceval in

  
  mt)
mkdir -p timingstats
./auxscripts/aolMeasureTiming > timingstats/timingReport.txt
;;
  
  
	sellat)
./auxscripts/selectLatestTelemetry
;;
  
	mkPSDs)
./auxscripts/processTelemetryPSDs
;;
  
	selB)
exec 3>&1;
blockSel=$(dialog --inputbox "Select block" 0 0 "$blockSel" 2>&1 1>&3);
exec 3>&-;
echo "$blockSel" > ./conf/conf_predcontr_blockSel.txt
;;

	PFord)
exec 3>&1;
PForder=$(dialog --inputbox "Select predictive filter order" 0 0 "$PForder" 2>&1 1>&3);
exec 3>&-;
echo "$PForder" > ./conf/conf_PForder.txt
;;




    ARPFb)
echo "./auxscripts/aolARPFblock \"./PredictiveControl/modeval_ol.fits\"  $blockSel $lat $PForder" > cmd.txt
./auxscripts/aolARPFblock "./PredictiveControl/modeval_ol.fits"  $blockSel $lat $PForder
;;

    ARPF)
echo "./auxscripts/aolARPF \"./PredictiveControl/modeval_ol.fits\" $lat $PForder" > cmd.txt
./auxscripts/aolARPF "./PredictiveControl/modeval_ol.fits" $lat $PForder
;;







	sellatC)
./auxscripts/selectLatestTelemetry -c
;;
  
  
  
  	PFapplyb)
echo "./auxscripts/aolApplyARPFblock \"./PredictiveControl/modeval_ol_C.fits\" \"./PredictiveControl/outPF.$blockSel.fits\" $blockSel $lat" > cmd.txt
./auxscripts/aolApplyARPF "./PredictiveControl/modeval_ol_C.fits" "./PredictiveControl/outPF.$blockSel.fits" $blockSel $lat
;;

  
	PFapply)
echo "./auxscripts/aolApplyARPF \"./PredictiveControl/modeval_ol_C.fits\" \"./PredictiveControl/outPF.fits\" $lat" > cmd.txt
./auxscripts/aolApplyARPF "./PredictiveControl/modeval_ol_C.fits" "./PredictiveControl/outPF.fits" $lat
;;




esac
;; 
   1) state="menutop";;   
  2) state="menuexit";;
   255) state="menuexit";;
esac

fi






