#!/bin/bash



if [ ! -v aolconfFLAG ]; then
echo "ERROR: This script should be called from aolconf main script"
exit
fi






function function_computeModesCM 
{
tmuxnameMCM="aol${LOOPNUMBER}mkmodes"
sleep 0.2
tmux new-session -s ${tmuxnameMCM} -d
sleep 0.2
tmux send-keys -t ${tmuxnameMCM} "" C-c
tmux send-keys -t ${tmuxnameMCM} "" C-m
tmux send-keys -t ${tmuxnameMCM} "./auxscripts/waitonfile FUNCTION_computeModesCM.block" C-m

logRunningProcessQ "aolmkmodes" "$tmuxnameMCM" "Compute control modes and control matrix (tmux session $tmuxname)"

computeModesCMscriptfile="function_computeModesCM.script"
rm $computeModesCMscriptfile
touch $computeModesCMscriptfile

echo "mkdir -p DMmodes" >> $computeModesCMscriptfile
echo "mkdir -p respM" >> $computeModesCMscriptfile
echo "mkdir -p contrM" >> $computeModesCMscriptfile
echo "mkdir -p contrMc" >> $computeModesCMscriptfile
echo "mkdir -p contrMcact" >> $computeModesCMscriptfile



echo "echo \"./auxscripts/aolmkmodes2 ${cpamax} -1 ${SVDlimall} ${mkModesMODE}\" >> aolcmd.txt"  >> $computeModesCMscriptfile
echo "./auxscripts/aolmkmodes2 ${cpamax} -1 ${SVDlimall} ${mkModesMODE}"  >> $computeModesCMscriptfile



datestr=`date -u +%Y-%m-%d_%H:%M:%S`

echo "cp ./mkmodestmp/fmodesall.fits DMmodes/DMmodes_${datestr}.fits"  >> $computeModesCMscriptfile
echo "echo \"DMmodes/DMmodes_${datestr}.fits\" > ./conf_staged/shmim_DMmodes.name.txt"  >> $computeModesCMscriptfile

echo "cp ./mkmodestmp/fmodesWFSall.fits respM/respM_${datestr}.fits"  >> $computeModesCMscriptfile
echo "echo \"respM/respM_${datestr}.fits\" > ./conf_staged/shmim_respM.name.txt"  >> $computeModesCMscriptfile

echo "cp ./mkmodestmp/cmatall.fits contrM/contrM_${datestr}.fits"  >> $computeModesCMscriptfile
echo "echo \"contrM/contrM_${datestr}.fits\" > ./conf_staged/shmim_contrM.name.txt"  >> $computeModesCMscriptfile

echo "cp ./mkmodestmp/NBmodes.txt ./conf_staged/param_NBmodes.txt" >> $computeModesCMscriptfile

for i in `seq 0 20`;
do
i2=$(printf "%02d" "$i")
fname="mkmodestmp/fmodes_${i2}.fits"
#if [ -e "$fname" ]; then
echo "if [ -f \"$fname\" ]; then cp ./mkmodestmp/fmodes_${i2}.fits DMmodes/DMmodes${i2}_${datestr}.fits; fi"  >> $computeModesCMscriptfile
echo "if [ -f \"$fname\" ]; then echo \"DMmodes/DMmodes${i2}_${datestr}.fits\" > ./conf_staged/shmim_DMmodes${i2}.name.txt; fi"  >> $computeModesCMscriptfile

echo "if [ -f \"$fname\" ]; then cp ./mkmodestmp/fmodesWFS_${i2}.fits respM/respM${i2}_${datestr}.fits; fi"  >> $computeModesCMscriptfile
echo "if [ -f \"$fname\" ]; then echo \"respM/respM${i2}_${datestr}.fits\" > ./conf_staged/shmim_respM${i2}.name.txt; fi"  >> $computeModesCMscriptfile

echo "if [ -f \"$fname\" ]; then cp ./mkmodestmp/cmat_${i2}.fits contrM/contrM${i2}_${datestr}.fits; fi"  >> $computeModesCMscriptfile
echo "if [ -f \"$fname\" ]; then echo \"contrM/contrM${i2}_${datestr}.fits\" > ./conf_staged/shmim_contrM${i2}.name.txt; fi"  >> $computeModesCMscriptfile

echo "if [ -f \"$fname\" ]; then cp ./mkmodestmp/cmatc_${i2}.fits contrMc/contrMc${i2}_${datestr}.fits; fi"  >> $computeModesCMscriptfile
echo "if [ -f \"$fname\" ]; then echo \"contrMc/contrMc${i2}_${datestr}.fits\" > ./conf_staged/shmim_contrMc${i2}.name.txt; fi"  >> $computeModesCMscriptfile

echo "if [ -f \"$fname\" ]; then cp ./mkmodestmp/cmatcact_${i2}.fits contrMcact/contrMcact${i2}_${datestr}.fits; fi"  >> $computeModesCMscriptfile
echo "if [ -f \"$fname\" ]; then echo \"contrMcact/contrMcact${i2}_${datestr}.fits\" > ./conf_staged/shmim_contrMcact${i2}_00.name.txt; fi"  >> $computeModesCMscriptfile
#fi
done
chmod +x $computeModesCMscriptfile
tmux send-keys -t $tmuxnameMCM "./$computeModesCMscriptfile" C-m


tmux send-keys -t $tmuxnameMCM "rm runproc/aolmkmodes.runproc" C-m


tmux send-keys -t $tmuxnameMCM "./aolconfscripts/aollog \"$LOOPNAME\" \"CM computation DONE\" &" C-m
tmux send-keys -t $tmuxnameMCM "dologext $LOOPNAME CM computation DONE &" C-m
}






function function_SharedMemLoadCM {
tmuxnameSMlCM="aol${LOOPNUMBER}SMloadCM"
echo "tmux new-session -s ${tmuxnameSMlCM} -d"
echo "CREATING SESSION : ${tmuxnameSMlCM}"
sleep 0.2
tmux new-session -s ${tmuxnameSMlCM} -d
sleep 0.2
tmux ls | grep ${tmuxnameSMlCM}
tmux send-keys -t ${tmuxnameSMlCM} "" C-c
tmux send-keys -t ${tmuxnameSMlCM} " " C-m

tmux send-keys -t ${tmuxnameSMlCM} "./auxscripts/waitonfile FUNCTION_SharedMemLoadCM.block" C-m
logRunningProcessQ "SharedMemLoadCM" "${tmuxnameSMlCM}" "Load control matrix into shared memory" 
tmux send-keys -t ${tmuxnameSMlCM} "aoconflogext \"LOAD CM to shared memory\"" C-m

# zonal calib
for imname in DMmodes respM contrM wfsref0
do
tmux send-keys -t ${tmuxnameSMlCM} "Fits2shm -c -p aol${LOOPNUMBER}_ ${imname}" C-m
done


NBmodeblocks=$( head -1 ./conf/param_NBmodeblocks.txt )
rm script_SharedMemLoadCM
touch script_SharedMemLoadCM
for i in `seq 0 $(( $NBmodeblocks - 1 ))`;
do
i2=$(printf "%02d" "$i")

echo "Fits2shm -c -p aol${LOOPNUMBER}_ DMmodes" >> script_SharedMemLoadCM	
echo "Fits2shm -c -p aol${LOOPNUMBER}_ respM" >> script_SharedMemLoadCM	
echo "Fits2shm -c -p aol${LOOPNUMBER}_ contrM" >> script_SharedMemLoadCM	


for imname in DMmodes${i2} respM${i2} contrM${i2} contrMc${i2} contrMcact${i2}_00 ; do
echo "Fits2shm -c -p aol${LOOPNUMBER}_ ${imname}" >> script_SharedMemLoadCM	
done
done

chmod +x script_SharedMemLoadCM
tmux send-keys -t ${tmuxnameSMlCM} "./script_SharedMemLoadCM" C-m	
tmux send-keys -t ${tmuxnameSMlCM} "rm runproc/SharedMemLoadCM.runproc" C-m	
}

