#!/bin/bash

EXPECTED_ARGS=2


if [ $# -ne $EXPECTED_ARGS ] || [ "$1" == "help" ]
then
  echo
  echo " command : $@"  
  echo
  echo "------ AO Linear Simulator ------"
  echo 
  echo "uses response matrix to simulate linear AO system"
  echo "Usage: $0 <GPUindex> <time interval>"
  echo 
  echo " INPUT <GPUindex>        : GPU index" 
  echo " INPUT <time interval>   : GPU index" 
  echo 
  echo 
  echo "Example: $0 5"
  echo 
  exit
fi



loopnb=$(cat LOOPNUMBER)


Cfits -n aol${loopnb}latency << EOF
readshmim aol${loopnb}_wfsim
readshmim aol${loopnb}_dmdisp
readshmim aol${loopnb}_zrespM
cudacoeff2map aol${loopnb}_zrespM aol${loopnb}_dmdisp ${GPUindex} aol${loopnb}_wfsim
exit
EOF
