#!/bin/bash


# number of arguments to script
NBARGS=0


# ======================= PROCESS NAME =================================
pname=`echo "$0" | sed "s/\.\///g"`
echo "pname = $pname"




function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : MAKE HADAMARD POKE MATRIX $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0"
echo ""
echo " $(tput bold)OPTIONAL INPUT:$(tput sgr0)"
echo "     HRM_DMmask.fits    DM active mask file - will be created if doesn't exist"
echo ""
echo " $(tput bold)REQUIRED:$(tput sgr0)"
echo "     dm     output file"
echo ""
echo "------------------------------------------------------------------------"
}



if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi


loopnb=$(cat LOOPNUMBER)

DMindex=$(cat ./conf/conf_DMindex.txt)
dmxsize=$(cat conf/conf_dm${DMindex}xsize.txt)
dmysize=$(cat conf/conf_dm${DMindex}ysize.txt)
echo "DM size = $dmxsize $dmysize"


if [ ! -f "./conf/HRM_DMmask.fits" ]; then
Cfits << EOF
#readshmim aol${loopnb}_dmC
#imstats aol${loopnb}_dmC
cx=0.5*${dmxsize}-0.5
cy=0.5*${dmysize}-0.5
rad=0.5*${dmxsize}+0.6
mkdisk dmmask ${dmxsize} ${dmysize} cx cy rad
savefits dmmask "!./conf/HRM_DMmask.fits"
itot(dmmask)
exit
EOF
fi


Cfits << EOF
loadfits "./conf/HRM_DMmask.fits" DMmask
aolmkH DMmask outim
savefits outim "!Hpoke.fits"
exit
EOF
