#! /bin/bash

EXPECTED_ARGS=0

if [ $# -ne $EXPECTED_ARGS ]
then
  echo
  echo "------ Align Pyramid camera -------"
  echo
  echo "   no argument"
  echo
  exit
fi

loopnb=$(cat LOOPNUMBER)
confnb=$(cat ./conf/conf_CONFNUMBER.txt)


pname0=$0
pname=${pname0#"./"}-$loopnb


Cfits -n pname << EOF
readshmim aol${loopnb}_wfsim
readshmim aol${loopnb}_wfsdark
readshmim aol${loopnb}_wfsref0
cp aol${loopnb}_wfsdark wfsdark
scexaopywfscamalign aol${loopnb}_wfsim
imdiff=imwfs-aol${loopnb}_wfsref0
savefits imdiff "!./tmp/imdiff.fits"
exit
EOF
