#! /bin/bash

EXPECTED_ARGS=0

if [ $# -ne $EXPECTED_ARGS ]
then
  echo
  echo "------ Measure illumination map ------"
  echo
  echo "  no arg"
  echo
  exit
fi

loopnb=$(cat LOOPNUMBER)

pname0=$0
pname=${pname0#"./"}-$loopnb




Cfits -n pname << EOF
aolnb $loopnb
aolmeasactmap 0.25 0.01 200 actmap
savefits actmap "!./conf/actmap.fits"
exit
EOF
