#!/bin/bash

EXPECTED_ARGS=0


if [ $# -ne $EXPECTED_ARGS ] || [ "$1" == "help" ]
then
  echo
  echo "------ Measure System Response Latency ------"
  echo 
  echo "Usage: $0 "
  echo 
  exit
fi



loopnb=$(cat LOOPNUMBER)


Cfits -n aol${loopnb}latency << EOF
readshmim aol${loopnb}_imWFS0
readshmim dmdisp1 
aoltestlat dmdisp1 aol${loopnb}_imWFS0
savefits _testwfsc "!test_latencyC.fits"
listim
exit
EOF
