#!/bin/bash

EXPECTED_ARGS=1


if [ $# -ne $EXPECTED_ARGS ] || [ "$1" == "help" ]
then
  echo
  echo "------ Measure System Response Latency ------"
  echo 
  echo "Usage: $0 <NBiter>"
  echo 
  echo " INPUT <NBiter>   : Number of interations" 
  echo 
  echo "Example: $0 5000"
  echo 
  exit
fi



loopnb=$(cat LOOPNUMBER)


Cfits -n aol${loopnb}latency << EOF
readshmim aol${loopnb}_imWFS0
readshmim dmdisp1 
aoltestlat dmdisp1 aol${loopnb}_wfsim $1
savefits _testwfsc "!test_latencyC.fits"
listim
exit
EOF
