#! /bin/bash
# args: <confindex> <maxCPA>

EXPECTED_ARGS=2

if [ $# -ne $EXPECTED_ARGS ]
then
  echo
  echo "------ CREATE MODES FOR AO LOOP ----"
  echo
  echo "Usage: mkModes <confindex> <maxCPA>"
  echo
  echo "  INPUT <confindex>  : configuration index (000, 001 ...)"
  echo "  INPUT <maxCPA>     : maximum spatial frequency in cycles per aperture"
  echo
  echo "EXAMPLE: mkModes 002 2.0"
  echo
  echo "  OUTPUT: ./conf<confindex>/fmodes.fits"
  echo "  OUTPUT: ./conf<confindex>/modescpa.fits"
  echo
  echo "NOTES :"
  echo "  USES (OPTIONAL) : ./conf/TPmask.fits"
  echo "                  Telescope pupil mask"
  echo "  USES (OPTIONAL) : ./conf/TPind.fits"
  echo "                  Modes to be excluded"
  echo
  exit
fi





loopnb=$(cat LOOPNUMBER)

pname0=$0
pname=${pname0#"./"}-$loopnb


mkdir -p conf$1

Cfits -n pname << EOF
aolnb $loopnb
loadfits "./conf/TPmask.fits" Mmask
loadfits "./conf/TPind.fits" emodes
aolmkmodes fmodes 50 $2 0.8 24.5 24.5 21.0 6.5
savefits fmodes "!./conf$1/fmodes.fits"
savefits modesfreqcpa "!./conf$1/modesfreqcpa.fits"
exit
EOF
