#!/bin/bash

NBARGS=0

filelist="aolconf"
dirlist="aolconfscripts auxscripts aohardsim"

printhelp ()
{
echo ""
echo "------------------- SYNC AOloopControl scripts ------------------"
echo " This function takes no argument"
echo ""
}


if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
        printhelp
if [ "$#" -ne $NBARGS ]; then
    echo "Illegal number of parameters ($NBARGS params required, $# entered)"
fi
        exit
fi

echo ""
echo "SYNCING AOloopControl scripts..."
echo ""


for file in ${filelist[*]}
do
	srcfile="$HOME/src/Cfits/src/AOloopControl/scripts/$file"
	echo "syncing file $srcfile -> $file"
	ln -fs $srcfile $file	
done

for dir in ${dirlist[*]}
do
	mkdir -p $dir
	srcdir="$HOME/src/Cfits/src/AOloopControl/scripts/$dir"
	for entry in "$srcdir"/*
	do
	filename="${entry##*/}"	
	echo "syncing directory $srcdir file $filename"
	ln -fs $entry ./$dir/$filename
	done
done



echo ""

