#!/bin/bash

#########################################################################################
##          LOAD RESP MATRIX TO SHM                                                    ##
#########################################################################################

execname="./AOloopControl"



RMZONALCALIBlist="wfsref0 zrespM wfsmap dmmap wfsmask dmmaskRM dmslaved dmmask"
#RMMODALCALIBlist="LODMmodes LOrespM LOwfsref0"





# CHECK IF ALREADY RUNNING
mkdir -p status
statfile="./status/stat_SMloadRespMON.txt"
if [ -a $statfile ]; then
	SMloadRespMONstat=$( cat $statfile )
else
	SMloadRespMONstat="OFF"
	echo "$SMloadRespMONstat" > $statfile
fi




if [ "$SMloadRespMONstat" = " ON" ]; then
echo "$0 already running"
exit
fi




##########################################
# READ REQUIRED PARAMETERS
##########################################

# READ LOOP NUMBER
if [ -f LOOPNUMBER ]; then
LOOPNUMBER=$( cat LOOPNUMBER )
else
LOOPNUMBER="7"
echo "$LOOPNUMBER" > LOOPNUMBER
fi




for imname in $RMZONALCALIBlist; do
Fits2shm -c -p aol${LOOPNUMBER}_ ${imname}
done

#for imname in $RMMODALCALIBlist; do
#Fits2shm -c -p aol${LOOPNUMBER}_ ${imname}
#done



echo "OFF" > $statfile
