#!/bin/bash




if [ ! -v FPaolconfFLAG ]; then
echo "ERROR: This script should be called from aolconf main script"
exit
fi





# =====================================================
# ===================== TOP MENU ======================
# =====================================================

if [ $state = "menutop" ]; then
stateok=1
dateUTC=$( date -u )
#aoconflog "$0 state = ${state}"
confselected=$(cat "./conf/conf_CONFNUMBER.txt")
menuname="TOP MENU\n [Active conf = ${confselected}]    [ $dateUTC ]"



menuitems+=( " " " ")
menuitems+=( " " " ")






# =====================================================================================================================
# ===================================  AO CONFIGURE AND CONTROL =======================================================
# =====================================================================================================================


stringcenter "AO CONFIGURE AND CONTROL"
menuitems+=( "1 ->" "\Zb\Zr$string\Zn" )
menuitems+=( " " " ")
menuitems+=( "M" "load all (M)emory" )
menuitems+=( "C" "(C)onfigure/link AO loop" )

menuitems+=( " " " ")
menuitems+=( " " " ")
menuitems+=( " " " ")



# =====================================================================================================================
# ===========================================  DATA LOGGING / ANALYSIS ================================================
# =====================================================================================================================


stringcenter "DATA LOGGING / ANALYSIS"
menuitems+=( "2 ->" "\Zb\Zr$string\Zn" )
menuitems+=( " " " ")
menuitems+=( "R" "Record / analyze")
menuitems+=( " " " ")
menuitems+=( " " " ")
menuitems+=( " " " ")


# =====================================================================================================================
# ===========================================  CUSTOM EXTERNAL SCRIPTS ================================================
# =====================================================================================================================


stringcenter "CUSTOM EXTERNAL SCRIPTS"
menuitems+=( "3 ->" "\Zb\Zr$string\Zn" )
menuitems+=( " " " ")
























dialog --colors --title "FP AO loop top menu  - LOOP ${LOOPNAME} (${LOOPNUMBER})  [$nbwlines x $nbwcols]" \
--ok-label "Select" \
--cancel-label "Exit" \
--default-item "${menutop_default}" \
 --menu "$menuname" \
 $nbwlines $nbwcols $nbwlines "${menuitems[@]}"  2> $tempfile


retval=$?
choiceval=$(cat $tempfile)
menutop_default="$choiceval"
case $retval in
   0) # button
	case $choiceval in



# =====================================================================================================================
# ===================================  AO CONFIGURE AND CONTROL =======================================================
# =====================================================================================================================

	M)
FPAOloadMem 1
;;


   	 C) state="menuconfigureloop";;
   	 

# =====================================================================================================================
# ===========================================  DATA LOGGING / ANALYSIS ================================================
# =====================================================================================================================
	R) state="menurecord" ;;


# =====================================================================================================================
# ===========================================  CUSTOM EXTERNAL SCRIPTS ================================================
# =====================================================================================================================
#   	 A) state="menualign";;
#   	 HC) state="menuhardwarecontrol";;

	esac;;
   1) state="menuexit";;   
   255) state="menuexit";;
esac
fi













