#!/bin/bash



# number of arguments to script
NBARGS=0


# ======================= PROCESS NAME =================================
pname=`echo "$0" | sed "s/\.\///g"`
echo "pname = $pname"





LOOPNAME="SCExAOFPAO"
LOOPNUMBER="2"

function printHELP {
echo "------------------------------------------------------------------------"
echo "$(tput bold) $pname : CONFIGURE AO LOOP FOR SCExAO FP $(tput sgr0)"
echo "------------------------------------------------------------------------"
echo "  Configures AO loop custom scripts and variables for SCExAO FP"
echo "   "
echo " $(tput bold)USAGE:$(tput sgr0)"
echo "     $0 [-h]"
echo ""
echo " $(tput bold)OPTIONS:$(tput sgr0)"
echo "     $(tput bold)-h$(tput sgr0)          help"
echo ""
echo "------------------------------------------------------------------------"
}




EXITSTATUS=0

function checkFile {
if [ -f $1 ]
  then
    echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr0)] File $(tput bold)$1$(tput sgr0) found"
   else
    echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] File $(tput bold)$1$(tput sgr0) not found"
    EXITSTATUS=1
fi
}

function checkDir {
if [ -d $1 ]
  then
    echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr0)] Directory $(tput bold)$1$(tput sgr0) found"
   else
    echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] Directory $(tput bold)$1$(tput sgr0) not found"
    EXITSTATUS=1
fi
}

function cmdexists()
{
  command -v "$1" >/dev/null 2>&1
}


function checkCommand {
if cmdexists $1; then
    echo "[$(tput setaf 2)$(tput bold)   OK   $(tput sgr0)] Command $(tput bold)$1$(tput sgr0) found"
else
    echo "[$(tput setaf 1)$(tput bold) FAILED $(tput sgr0)] Command $(tput bold)$1$(tput sgr0) not installed.  Aborting."; EXITSTATUS=1;
fi

}


# ================= OPTIONS =============================

while getopts :h FLAG; do
  case $FLAG in
    h)  #show help
      printHELP
      exit
      ;;
    \?) #unrecognized option - show help
      echo -e \\n"Option -${BOLD}$OPTARG${NORM} not allowed."
      printHELP
      ;;
  esac
done

shift $((OPTIND-1)) 

### End getopts code ###








if [ "$1" = "help" ] || [ "$#" -ne $NBARGS ]; then
if [ "$#" -ne $NBARGS ]; then
    echo "$(tput setaf 1)$(tput bold) Illegal number of parameters ($NBARGS params required, $# entered) $(tput sgr0)"
fi
printHELP
        exit
fi


# ======================= FILE NAMES ===========================================
FPAOloopAlign_file="FPaocustomscripts/FPAOloopAlign_${LOOPNAME}.bash" 
takedark_file="FPaocustomscripts/takedark_${LOOPNAME}"
cpuconfig_file="FPaocustomscripts/cpuconfig_${LOOPNAME}"

# ======================= CHECK REQUIRED FILES =================================
echo ""
checkFile $FPAOloopAlign_file
checkFile $takedark_file
checkFile $cpuconfig_file




if [ $EXITSTATUS -eq 1 ]; then
echo ""
echo "$(tput setaf 1)$(tput bold) REQUIRED FILES, COMMANDS NOT FOUND: EXITING $(tput sgr0)"
echo ""
exit
else
echo ""
fi





echo $LOOPNAME > LOOPNAME
echo $LOOPNUMBER > LOOPNUMBER


rm FPaocustomscripts/FPAOloopAlign.bash &> /dev/null
ln -s $PWD/$FPAOloopAlign_file FPaocustomscripts/FPAOloopAlign.bash 

rm FPaocustomscripts/takedark &> /dev/null
ln -s $PWD/$takedark_file FPaocustomscripts/takedark 

rm FPaocustomscripts/cpuconfig &> /dev/null
ln -s $PWD/$cpuconfig_file FPaocustomscripts/cpuconfig 




mkdir -p conf
DMindex="00"
echo "$DMindex" > ./conf/conf_DMindex.txt
echo "50" > ./conf/conf_dm${DMindex}xsize.txt
echo "50" > ./conf/conf_dm${DMindex}ysize.txt
echo "dm${DMindex}disp06" > ./conf/conf_dmC_name.txt # DM control channel
echo "dm${DMindex}disp07" > ./conf/conf_dmRM_name.txt # DM actuation channel for RM matrix

echo "ircam1" > ./conf/conf_wfsim_name.txt

echo "0.02" >./conf/conf_RMamplum.txt    
echo "2" >./conf/conf_RMdelayfr.txt
echo "5" >./conf/conf_RMfrave.txt 
echo "3" >./conf/conf_RMexfr.txt      

